services:
  myamigurumi.identity.app:
    image: myamigurumi.identity.app
    build:
      context: .
      dockerfile: ../dotnet/MyAmigurumi.Identity.App/Dockerfile
    ports:
      - "6000:6001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=localhost,1433;Database=ma_identity_db;User Id=sa;Password=Pass123$;TrustServerCertificate=True;
